" Configuration file for vim
set modelines=0		" CVE-2007-2438

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility

""""""""""""""""""""""""""""""""""
" Vim-Plug Plugin Manager Stuff "
""""""""""""""""""""""""""""""""""
set runtimepath+=~/.vim/autoload/

" Auto install Vim Plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/plugged/')

" Plugins Installation
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-dispatch', {'for': 'python'}
Plug 'drgarcia1986/python-compilers.vim', {'for': 'python'}
Plug 'fatih/vim-go', {'for': 'go'}

call plug#end()

filetype plugin indent on

""""""""""""""""""""""""""""""""
" Tab and indentation settings "
""""""""""""""""""""""""""""""""
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set softtabstop=4
set smarttab

set backspace=eol,start,indent

"""""""""""""""""""""""""
" Command mode settings "
"""""""""""""""""""""""""
set wildmenu
set wildmode=list:longest,list:full

"""""""""""""""""""""""
" Don't create backup "
"""""""""""""""""""""""
set nobackup
set nowritebackup
set noswapfile

"""""""""""""""""""
" Search settings "
"""""""""""""""""""
set hlsearch
set incsearch
set ignorecase

"""""""""""""""""""
" Visual settings "
"""""""""""""""""""
" colors
set t_Co=256

colorscheme desert
syntax on

" color column (if set)
highlight ColorColumn ctermbg=8

" show cursor line
set cursorline

" show linenumber
set nu

" To help in using of airline
set laststatus=2

" show traling spaces
set list
set listchars=trail:-,tab:\ \ ,

""""""""""""
" Commands "
""""""""""""
" Save with root privilege
command! Wroot :execute ':silent w !sudo tee % > /dev/null' | :edit!

" remove trailing whitespaces
command! CleanTrail :%s/\s\+$//e

" fix python import (based on isort)
command! -nargs=* -range=% FixPythonImports :<line1>,<line2>! isort <args> -

""""""""""
" Abbrev "
""""""""""
" Or I use this abbrevs or remove my shift key
cnoreabbrev W! w!
cnoreabbrev Q! q!
cnoreabbrev Qall! qall!
cnoreabbrev Wq wq
cnoreabbrev Wa wa
cnoreabbrev wQ wq
cnoreabbrev WQ wq
cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev Qall qall

"""""""""""""""""
" Abbreviations "
"""""""""""""""""
iab gL logger = logging.getLogger(__name__)
iab pdb import pdb; pdb.set_trace()

"""""""""""""""""
" Auto commands "
"""""""""""""""""
" show colorcolumn for column 80 in python files
augroup python
    au!
    autocmd FileType python set colorcolumn=80
    autocmd FileType python compiler flake8
    autocmd BufWrite *.py :Dispatch
augroup END

" auto syntax for *.md files
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

"""""""""""""""""""
" Omni completion "
"""""""""""""""""""
set omnifunc=syntaxcomplete#Complete

""""""""""""""""""""
" Plugins Settings "
""""""""""""""""""""
" Netrw
let g:netrw_list_hide= '.*\.swp$,.*\.pyc,__pycache__,.DS_Store'
let g:netrw_localrmdir="rm -r"

" Airline
let g:airline_theme = 'term'
let g:airline_enable_branch = 1
let g:airline_enable_syntastic = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_left_sep = '▶'
let g:airline_left_alt_sep = '»'
let g:airline_right_sep = '◀'
let g:airline_right_alt_sep = '«'
let g:airline#extensions#readonly#symbol = '⊘'

" Vim-Go
" run GoImports on save
let g:go_fmt_command = "goimports"
